
const	productData = [
        {
          price: 49.99,
          address: '123 Main Street, City, State',
          sellerid: 'seller001',
          description: 'A high-quality laptop bag with multiple compartments.',
          title: 'Laptop Bag',
          category: 'Accessories',
          type: 'selling',
          uuid: '1e8e48d6-7f7e-4a29-a0e1-08f7cacf925f',
        },
        {
          price: 199.99,
          address: '456 Elm Avenue, Town, State',
          sellerid: 'seller002',
          description: 'An elegant wristwatch with a leather strap.',
          title: 'Leather Wristwatch',
          category: 'Fashion',
          type: 'donating',
          uuid: 'b743d6a0-334c-49a1-a0e2-5b50dabf0df0',
        },
        {
          price: 29.95,
          address: '789 Oak Road, Village, State',
          sellerid: 'seller003',
          description: 'A set of 6 durable glass tumblers for everyday use.',
          title: 'Glass Tumbler Set',
          category: 'Kitchen',
          type: 'borrowing',
          uuid: 'c845d84c-2c0c-4a6b-a0e3-1b51bdcf6b62',
        },
        {
          price: 49.99,
          address: '123 Main Street, City, State',
          sellerid: 'seller001',
          description: 'A high-quality laptop bag with multiple compartments.',
          title: 'Laptop Bag',
          category: 'Accessories',
          type: 'borrowing',
          uuid: 'unique-uuid-1',
        },
        {
          price: 199.99,
          address: '456 Elm Avenue, Town, State',
          sellerid: 'seller002',
          description: 'An elegant wristwatch with a leather strap.',
          title: 'Leather Wristwatch',
          category: 'Fashion',
          type: 'borrowing',
          uuid: 'unique-uuid-2',
        },
        {
          price: 29.95,
          address: '789 Oak Road, Village, State',
          sellerid: 'seller003',
          description: 'A set of 6 durable glass tumblers for everyday use.',
          title: 'Glass Tumbler Set',
          category: 'Kitchen',
          type: 'borrowing',
          uuid: 'unique-uuid-3',
        },
        {
          price: 399.99,
          address: '101 Pine Lane, Countryside, State',
          sellerid: 'seller004',
          description: 'A powerful smartphone with an impressive camera.',
          title: 'Smartphone',
          category: 'Electronics',
          type: 'borrowing',
          uuid: 'unique-uuid-4',
        },
        {
          price: 79.99,
          address: '210 Cedar Street, Suburbia, State',
          sellerid: 'seller005',
          description: 'A comfortable office chair with ergonomic design.A comfortable office chair with ergonomic design.A comfortable office chair with ergonomic design.A comfortable office chair with ergonomic design.A comfortable office chair with ergonomic design.A comfortable office chair with ergonomic design.',
          title: 'Office Chair',
          category: 'Furniture',
          type: 'borrowing',
          uuid: 'unique-uuid-5',
        },
        {
          price: 149.95,
          address: '555 Maple Avenue, Metropolis, State',
          sellerid: 'seller006',
          description: 'A versatile set of professional-grade cookware.',
          title: 'Cookware Set',
          category: 'Kitchen',
          type: 'borrowing',
          uuid: 'unique-uuid-6',
        },
        {
          price: 9.99,
          address: '777 Birch Lane, Hamlet, State',
          sellerid: 'seller007',
          description: 'A collection of classic novels by renowned authors.',
          title: 'Book Set',
          category: 'Books',
          type: 'borrowing',
          uuid: 'unique-uuid-7',
        },
        {
          price: 59.99,
          address: '333 Walnut Street, Coastal Town, State',
          sellerid: 'seller008',
          description: 'A comfortable office chair with ergonomic design.A comfortable office chair with ergonomic design.A comfortable office chair with ergonomic design.A comfortable office chair with ergonomic design.A comfortable office chair with ergonomic design.A comfortable office chair with ergonomic design.A cozy throw blanket perfect for chilly evenings.',
          title: 'Throw Blanket',
          category: 'Home Decor',
          type: 'borrowing',
          uuid: 'unique-uuid-8',
        },
        {
          price: 49.99,
          address: '888 Willow Road, Mountain Village, State',
          sellerid: 'seller009',
          description: 'A set of noise-canceling headphones for immersive audio.',
          title: 'Headphones',
          category: 'Electronics',
          type: 'selling',
          uuid: 'unique-uuid-9',
        },
        {
          price: 19.99,
          address: '444 Spruce Avenue, Lakeside, State',
          sellerid: 'seller010',
          description: 'A collection of colorful art supplies for creative projects.',
          title: 'Art Supplies Set',
          category: 'Art & Craft',
          type: 'selling',
          uuid: 'unique-uuid-10',
        },
        {
          price: 19.99,
          address: '444 Spruce Avenue, Lakeside, State',
          sellerid: 'seller010',
          description: 'A collection of colorful art supplies for creative projects.',
          title: 'Art Supplies Set',
          category: 'Art & Craft',
          type: 'selling',
          uuid: 'unique-uuid-11',
        },
        {
          price: 19.99,
          address: '444 Spruce Avenue, Lakeside, State',
          sellerid: 'seller010',
          description: 'A collection of colorful art supplies for creative projects.',
          title: 'Art Supplies Set',
          category: 'Art & Craft',
          type: 'selling',
          uuid: 'unique-uuid-12',
        },
        {
          price: 49.99,
          address: '123 Main Street, City, State',
          sellerid: 'seller001',
          description: 'A high-quality laptop bag with multiple compartments.',
          title: 'Laptop Bag',
          category: 'Accessories',
          type: 'selling',
          uuid: 'unique-uuid-13',
        },
        {
          price: 199.99,
          address: '456 Elm Avenue, Town, State',
          sellerid: 'seller002',
          description: 'An elegant wristwatch with a leather strap.',
          title: 'Leather Wristwatch',
          category: 'Fashion',
          type: 'donating',
          uuid: 'unique-uuid-14',
        },
        {
          price: 29.95,
          address: '789 Oak Road, Village, State',
          sellerid: 'seller003',
          description: 'A set of 6 durable glass tumblers for everyday use.',
          title: 'Glass Tumbler Set',
          category: 'Kitchen',
          type: 'borrowing',
          uuid: 'unique-uuid-15',
        },
        {
          price: 49.99,
          address: '123 Main Street, City, State',
          sellerid: 'seller001',
          description: 'A high-quality laptop bag with multiple compartments.',
          title: 'Laptop Bag',
          category: 'Accessories',
          type: 'borrowing',
          uuid: 'unique-uuid-16',
        },
        {
          price: 199.99,
          address: '456 Elm Avenue, Town, State',
          sellerid: 'seller002',
          description: 'An elegant wristwatch with a leather strap.',
          title: 'Leather Wristwatch',
          category: 'Fashion',
          type: 'borrowing',
          uuid: 'unique-uuid-17',
        },
        {
          price: 29.95,
          address: '789 Oak Road, Village, State',
          sellerid: 'seller003',
          description: 'A set of 6 durable glass tumblers for everyday use.',
          title: 'Glass Tumbler Set',
          category: 'Kitchen',
          type: 'borrowing',
          uuid: 'unique-uuid-18',
        },
        {
          price: 399.99,
          address: '101 Pine Lane, Countryside, State',
          sellerid: 'seller004',
          description: 'A powerful smartphone with an impressive camera.',
          title: 'Smartphone',
          category: 'Electronics',
          type: 'borrowing',
          uuid: 'unique-uuid-19',
        },
        {
          price: 79.99,
          address: '210 Cedar Street, Suburbia, State',
          sellerid: 'seller005',
          description: 'A comfortable office chair with ergonomic design.A comfortable office chair with ergonomic design.A comfortable office chair with ergonomic design.A comfortable office chair with ergonomic design.A comfortable office chair with ergonomic design.A comfortable office chair with ergonomic design.',
          title: 'Office Chair',
          category: 'Furniture',
          type: 'borrowing',
          uuid: 'unique-uuid-20',
        },
        {
          price: 149.95,
          address: '555 Maple Avenue, Metropolis, State',
          sellerid: 'seller006',
          description: 'A versatile set of professional-grade cookware.',
          title: 'Cookware Set',
          category: 'Kitchen',
          type: 'borrowing',
          uuid: 'unique-uuid-21',
        },
        {
          price: 9.99,
          address: '777 Birch Lane, Hamlet, State',
          sellerid: 'seller007',
          description: 'A collection of classic novels by renowned authors.',
          title: 'Book Set',
          category: 'Books',
          type: 'borrowing',
          uuid: 'unique-uuid-22',
        },
        {
          price: 59.99,
          address: '333 Walnut Street, Coastal Town, State',
          sellerid: 'seller008',
          description: 'A comfortable office chair with ergonomic design.A comfortable office chair with ergonomic design.A comfortable office chair with ergonomic design.A comfortable office chair with ergonomic design.A comfortable office chair with ergonomic design.A comfortable office chair with ergonomic design.A cozy throw blanket perfect for chilly evenings.',
          title: 'Throw Blanket',
          category: 'Home Decor',
          type: 'borrowing',
          uuid: 'unique-uuid-23',
        },
        {
          price: 49.99,
          address: '888 Willow Road, Mountain Village, State',
          sellerid: 'seller009',
          description: 'A set of noise-canceling headphones for immersive audio.',
          title: 'Headphones',
          category: 'Electronics',
          type: 'selling',
          uuid: 'unique-uuid-24',
        },
        {
          price: 19.99,
          address: '444 Spruce Avenue, Lakeside, State',
          sellerid: 'seller010',
          description: 'A collection of colorful art supplies for creative projects.',
          title: 'Art Supplies Set',
          category: 'Art & Craft',
          type: 'selling',
          uuid: 'unique-uuid-25',
        },
        {
          price: 19.99,
          address: '444 Spruce Avenue, Lakeside, State',
          sellerid: 'seller010',
          description: 'A collection of colorful art supplies for creative projects.',
          title: 'Art Supplies Set',
          category: 'Art & Craft',
          type: 'selling',
          uuid: 'unique-uuid-26',
        },
        {
          price: 19.99,
          address: '444 Spruce Avenue, Lakeside, State',
          sellerid: 'seller010',
          description: 'A collection of colorful art supplies for creative projects.',
          title: 'Art Supplies Set',
          category: 'Art & Craft',
          type: 'selling',
          uuid: 'unique-uuid-27',
        },
    ]

export default productData ;
